### ISSUE TITLE
Bring back distribution moments

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5078]
With #4983 and #5087 finished, it's a good time to bring back moments for our distributions for more stable starting points.

With this we can then do the switch in #5009

We should also update the distribution developer guide to mention the implementation of moments: https://github.com/pymc-devs/pymc/blob/main/docs/source/developer_guide_implementing_distribution.md

***
# How to help?

1. This PR should give a template on how to implement and test new moments for distributions: https://github.com/pymc-devs/pymc/pull/5087/files
2. In most cases we should be able to copy the moments we were using in the [V3 branch](https://github.com/pymc-devs/pymc/tree/v3/pymc3/distributions). For example here is what we were doing for the `Beta`
    https://github.com/pymc-devs/pymc/blob/efbaccee94159de0a15b04baf84b1250047f132a/pymc3/distributions/continuous.py#L1235
  2.1 We used to have multiple moments for some distributions such as `mean`, `median`, `mode`. We only support one moment now, and probably the "higher-order" one is the most useful (that is `mean` > `median` > `mode`)... You might need to truncate the moment if you are dealing with a discrete distribution.
  2.2 We left some of these moments commented out inside the distribution `dist` classmethod. Make sure they are removed when you implement them! https://github.com/pymc-devs/pymc/blob/8f3636daf7d9946f6eca4717f3bb0c6d77d9c6e9/pymc/distributions/continuous.py#L538-L539
3. We have to be careful with `size != None` and broadcasting properly when when some parameters that are not used in the `moment` may nevertheless inform about the shape of the distribution. E.g. `pm.Normal.dist(mu=0, sigma=np.arange(1, 6))` returns a moment of `[mu, mu, mu, mu, mu]`. Again #5087 should give some template to think about this https://github.com/pymc-devs/pymc/blob/8f3636daf7d9946f6eca4717f3bb0c6d77d9c6e9/pymc/distributions/continuous.py#L546-L550
  3.1 In the case where you have to manually broadcast the parameters with each other it's important to add test conditions that would fail if you were not to do that. A straightforward way to do this is to make the used parameter a scalar, the unused one(s) a vector (one at a time) and size `None`
 
4. Just to keep things uniform*ish*, please add the `get_moment` immediately below the `dist` classmethod and before `logp` or `logcdf` methods.
5. New tests have to be added in `test_distributions_moments.py`. Make sure to test different combinations of size and broadcasting to cover the cases mentioned in point 3.
6. Don't hesitate to ask any questions. **You can grab as many distributions to implement moments as you want. Just make sure to write in this issue so that we can keep track of it.**
7. Profit with your new open source KARMA!

## The following distributions don't have a moment method implemented:

- [x] pymc.distributions.continuous.Beta #5145
- [x] pymc.distributions.continuous.Kumaraswamy #5147
- [x] pymc.distributions.continuous.Exponential #5147
- [x] pymc.distributions.continuous.Laplace #5147
- [x] pymc.distributions.continuous.StudentT #5147
- [x] pymc.distributions.continuous.Cauchy #5147
- [x] pymc.distributions.continuous.HalfCauchy https://github.com/pymc-devs/pymc/pull/5148
- [x] pymc.distributions.continuous.Gamma https://github.com/pymc-devs/pymc/pull/5148
- [x] pymc.distributions.continuous.Weibull https://github.com/pymc-devs/pymc/pull/5148
- [x] pymc.distributions.continuous.LogNormal https://github.com/pymc-devs/pymc/pull/5148
- [x] pymc.distributions.continuous.HalfStudentT https://github.com/pymc-devs/pymc/pull/5152
- [x] pymc.distributions.continuous.ChiSquared https://github.com/pymc-devs/pymc/pull/5154
- [x] pymc.distributions.continuous.Wald #5161
- [x] pymc.distributions.continuous.Pareto #5161
- [x] pymc.distributions.continuous.InverseGamma #5199 
- [x] pymc.distributions.continuous.ExGaussian  #5165
- [x] pymc.distributions.continuous.VonMises #5232 
- [x] pymc.distributions.discrete.Binomial https://github.com/pymc-devs/pymc/pull/5150
- [x] pymc.distributions.discrete.BetaBinomial #5175 
- [x] pymc.distributions.discrete.Poisson https://github.com/pymc-devs/pymc/pull/5150
- [x] pymc.distributions.discrete.NegativeBinomial  #5163
- [x] pymc.distributions.discrete.Constant  #5156 
- [x] pymc.distributions.discrete.ZeroInflatedPoisson #5163
- [x] pymc.distributions.discrete.ZeroInflatedNegativeBinomial #5206 
- [x] pymc.distributions.discrete.ZeroInflatedBinomial #5163
- [x] pymc.distributions.discrete.DiscreteUniform #5167
- [x] pymc.distributions.discrete.Geometric #5158
- [x] pymc.distributions.discrete.HyperGeometric #5167
- [x] pymc.distributions.discrete.Categorical #5176 
- [x] pymc.distributions.distribution.DensityDist #5159
- [x] pymc.distributions.multivariate.MvNormal #5171 
- [x] pymc.distributions.multivariate.MatrixNormal #5173 
- [x] pymc.distributions.multivariate.KroneckerNormal #5235
- [x] pymc.distributions.multivariate.MvStudentT #5173 
- [x] pymc.distributions.multivariate.Dirichlet #5174 
- [x] pymc.distributions.multivariate.Multinomial #5201 
  - Note: This distribution had tests for the `mode` in `test_distributions.py` which should be moved/refactored to `test_distributions_moments.py` 
  - https://github.com/pymc-devs/pymc/blob/bdd4d1992f11cab9202774b14b8044ddf0cb7674/pymc/tests/test_distributions.py#L2151
  - https://github.com/pymc-devs/pymc/blob/bdd4d1992f11cab9202774b14b8044ddf0cb7674/pymc/tests/test_distributions.py#L2189
- [x] pymc.distributions.multivariate.DirichletMultinomial #5225 
- [x] pymc.distributions.continuous.AsymmetricLaplace #5188
- [x] pymc.distributions.continuous.SkewNormal #5188
- [x] pymc.distributions.continuous.Triangular #5180 
- [x] pymc.distributions.discrete.DiscreteWeibull #5407
- [x] pymc.distributions.continuous.Gumbel #5180 
- [x] pymc.distributions.continuous.Logistic #5157 
- [x] pymc.distributions.continuous.LogitNormal #5180 
- [x] pymc.distributions.continuous.Interpolated #5222 
- [x] pymc.distributions.continuous.Rice #5190
- [x] pymc.distributions.continuous.Moyal #5179 
- [x] pymc.distributions.simulator.Simulator #5208
- [x] pymc.distributions.multivariate.CAR  #5220 
- [x] pymc.distributions.continuous.PolyaGamma  #5193
- [x] pymc.bart.BART #5211

**Comment by ricardoV94** [comment]
@twiecki I updated #5087 which includes a possible template for adding and testing moments. Once we merge that, we can use it as an example

**Comment by ricardoV94** [comment]
Updated the top comment with a list of missing moments and some instructions

**Comment by michaeloriordan** [comment]
I'll add a PR for pymc.distributions.continuous.Beta as a warmup https://github.com/pymc-devs/pymc/pull/5145. Will work on some more if I got this one right! 😄

**Comment by michaeloriordan** [comment]
I'll work on the next 5 distributions on the list. PR here https://github.com/pymc-devs/pymc/pull/5147
- pymc.distributions.continuous.Kumaraswamy
- pymc.distributions.continuous.Exponential
- pymc.distributions.continuous.Laplace
- pymc.distributions.continuous.StudentT
- pymc.distributions.continuous.Cauchy

**Comment by lucianopaz** [comment]
I'll do:
- HalfCauchy
- Gamma
- Weibull
- LogNormal

**Comment by farhanreynaldo** [comment]
I would like to take on:
* Binomial
* Poisson

**Comment by twiecki** [comment]
Thanks @farhanreynaldo!

**Comment by azihna** [comment]
I'd like to work on HalfStudentT

**Comment by ricardoV94** [comment]
> I'd like to work on HalfStudentT

Sure go ahead :)

**Comment by patel-zeel** [comment]
I have added ChiSquared moment.

**Comment by theorashid** [comment]
I'll take NegativeBinomial, ZeroInflatedPoisson, ZeroInflatedBinomial. Bear with me though as it's my first PR

**Comment by sagartomar** [comment]
Sent a PR for geometric distribution in #5158

**Comment by lucianopaz** [comment]
I’ll do the DensityDist get moment

**Comment by sagartomar** [comment]
I would also like to work on:
- Triangular
- Gumbel
- LogitNormal

**Comment by ricardoV94** [comment]
> I would also like to work on:
> - Triangular
> - Gumbel
> - LogitNormal
> 

Go ahead!

**Comment by karm-patel** [comment]
I would like to try ExGaussian!

**Comment by ricardoV94** [comment]
> I would like to try ExGaussian!

You can go ahead @karm216

**Comment by larryshamalama** [comment]
I can perhaps start with `pm.Dirichlet` and take on more multivariate distributions if things go well!

**Comment by ricardoV94** [comment]
> I can perhaps start with `pm.Dirichlet` and take on more multivariate distributions if things go well!

That would be great. I am marking the `Dirichlet` as taken, let me know when you want to tackle others

**Comment by yadav-sachin** [comment]
I am working on pymc.distributions.multivariate.MvNormal

**Comment by patel-zeel** [comment]
I'd like to take on:
* pymc.distributions.multivariate.MatrixNormal
* pymc.distributions.multivariate.MvStudentT

**Comment by ricardoV94** [comment]
> I'd like to take on:
> * pymc.distributions.multivariate.MatrixNormal
> * pymc.distributions.multivariate.MvStudentT

Go ahead :)

**Comment by Domenico89** [comment]
I would like to try VonMises

**Comment by twiecki** [comment]
@Domenico89 It's yours :)

**Comment by morganstrom** [comment]
I'm taking on BetaBinomial

**Comment by ricardoV94** [comment]
> I'm taking on BetaBinomial

Noted

**Comment by jlopezarriaza** [comment]
I'll give the `Moyal` distribution a shot and help out with others. Note this is my first PR so it may take me a moment. 

I've opened a PR here 
https://github.com/pymc-devs/pymc/pull/5179

**Comment by jlopezarriaza** [comment]
Now that I have one under my belt, I can take the AsymmetricLaplace and SkewNormal and have a PR open here in a day or two. 

PR opened here:
https://github.com/pymc-devs/pymc/pull/5188

**Comment by ricardoV94** [comment]
> Now that I have one under my belt, I can take the AsymmetricLaplace and SkewNormal and have a PR open here in a day or two.

I have marked them for you @jlopezarriaza

**Comment by morganstrom** [comment]
I'm working on InverseGamma now

**Comment by morganstrom** [comment]
OK I'm getting warmed up now! Let me do Multinomial and DirichletMultinomial as well please!

**Comment by anirudhacharya** [comment]
I will add `KroneckerNormal`, `Wishart`, `DiscreteWeibull`.

**Comment by ricardoV94** [comment]
> OK I'm getting warmed up now! Let me do Multinomial and DirichletMultinomial as well please!

Noted @morganstrom

**Comment by ricardoV94** [comment]
> I will add `KroneckerNormal`, `Wishart`, `DiscreteWeibull`.

Noted @anirudhacharya

**Comment by sagartomar** [comment]
I will also also add ZeroInflatedNegativeBinomial

**Comment by ricardoV94** [comment]
> I will also also add ZeroInflatedNegativeBinomial

Thanks!

**Comment by jlopezarriaza** [comment]
I went ahead and tackled the Rice distribution.
Hoping doing them piecemeal isn't a problem, squeezing them in as I have time. 
PR: https://github.com/pymc-devs/pymc/pull/5190

**Comment by jlopezarriaza** [comment]
Took a stab at the PolyaGamma Distribution
PR : https://github.com/pymc-devs/pymc/pull/5193

**Comment by larryshamalama** [comment]
I can take `Interpolated`!

**Comment by ricardoV94** [comment]
@zoj613 @ckrapu @aerubanov would any of you be interested in implementing the `get_moment` for the `CAR` distribution? Asking because you have done PRs related to this distribution in the past :)

**Comment by ricardoV94** [comment]
@aloctavodia We need a moment for `BARTRV`s, which can be just returning the `RV` if you want the moment to be a draw from the prior (or anything else that makes sense). Do you have time to open a PR for this?

**Comment by zoj613** [comment]
> @zoj613 @ckrapu @aerubanov would any of you be interested in implementing the `get_moment` for the `CAR` distribution? Asking because you have done PRs related to this distribution in the past :)

I will have a look at the source this coming weekend and see if I can take a stab at it.

**Comment by aloctavodia** [comment]
@ricardoV94 Yes,  I will.

**Comment by twiecki** [comment]
Last one is CAR! 🥳

**Comment by zoj613** [comment]
> Last one is CAR! partying_face

If I remember the CAR distribution correctly, it should just return the `mu` parameter for the moment, like in the example of the OP?

**Comment by ricardoV94** [comment]
> > Last one is CAR! partying_face
> 
> If I remember the CAR distribution correctly, it should just return the `mu` parameter for the moment, like in the example of the OP?

Yeah I think so. Just have to make sure it has the right shape. Is it exactly the same as the MvNormal moment?

**Comment by zoj613** [comment]
> > > Last one is CAR! partying_face
> > 
> > 
> > If I remember the CAR distribution correctly, it should just return the `mu` parameter for the moment, like in the example of the OP?
> 
> Yeah I think so. Just have to make sure it has the right shape. Is it exactly the same as the MvNormal moment?

Yeah, as far as I understand. The CAR is modeled using a multivariate normal distribution with a specific covariance matrix. So it should be identical to the MvNormal if both accept the same kind of parameters `mu` and `cov`.

**Comment by ricardoV94** [comment]
> Yeah, as far as I understand. The CAR is modeled using a multivariate normal distribution with a specific covariance matrix. So it should be identical to the MvNormal if both accept the same kind of parameters `mu` and `cov`.

Sounds good. Do you want to open a PR for it? I'll mark it above as taken.

**Comment by zoj613** [comment]
> > Yeah, as far as I understand. The CAR is modeled using a multivariate normal distribution with a specific covariance matrix. So it should be identical to the MvNormal if both accept the same kind of parameters `mu` and `cov`.
> 
> Sounds good. Do you want to open a PR for it? I'll mark it above as taken.

Sure, i'll open one.

**Comment by ricardoV94** [comment]
All distributions have been taken. I've just unchecked those that don't yet have a PR open to facilitate tracking in the final stage.

**Comment by ricardoV94** [comment]
> I would like to try VonMises

@Domenico89 Any progress on this?

**Comment by ricardoV94** [comment]
> I will add `KroneckerNormal`, `Wishart`, `DiscreteWeibull`.

@anirudhacharya Any progress on this?

**Comment by Domenico89** [comment]
> > I would like to try VonMises
> 
> @Domenico89 Any progress on this?

@ricardoV94 I should have an implementation for it, but I am getting an error for some values of the test parameters for which I haven't managed to figure out the reason yet

**Comment by ricardoV94** [comment]
> > > I would like to try VonMises
> > 
> > @Domenico89 Any progress on this?
> 
> @ricardoV94 I should have an implementation for it, but I am getting an error for some values of the test parameters for which I haven't managed to figure out the reason yet

Feel free to open a PR with what you have so far and we will help you there

**Comment by anirudhacharya** [comment]
> @anirudhacharya Any progress on this?

I will finish up the tests and raise a PR by tomorrow.

**Comment by anirudhacharya** [comment]
@ricardoV94 [Wishart Distribution documentation](https://docs.pymc.io/en/v3/api/distributions/multivariate.html?highlight=KroneckerNormal#pymc3.distributions.multivariate.Wishart) says - `This distribution is unusable in a PyMC3 model` should I be adding tests and moments for it? Is there an example usage I can look at for writing the tests?

**Comment by twiecki** [comment]
@anirudhacharya No, we don't need that for Wishart.

**Comment by anirudhacharya** [comment]
@ricardoV94 I am having trouble writing tests for the `DiscreteWeibull` distribution.

Is there some example usage of this distribution that I can check out? The documentation did not provide any - https://docs.pymc.io/en/v3/api/distributions/discrete.html?highlight=Weibull#pymc3.distributions.discrete.DiscreteWeibull

**Comment by ricardoV94** [comment]
> @ricardoV94 I am having trouble writing tests for the `DiscreteWeibull` distribution.
> 
> Is there some example usage of this distribution that I check out? The documentation did not provide any - https://docs.pymc.io/en/v3/api/distributions/discrete.html?highlight=Weibull#pymc3.distributions.discrete.DiscreteWeibull

Feel free to open a PR with what you have so far, it will be easier to help you then. 

I don't know about any examples using the distribution, but the check_logp test gives an indication of some values and parameters that are being tested successfully: https://github.com/pymc-devs/pymc/blob/a50b386f73df3960e2a7b45d0c2e24831715907c/pymc/tests/test_distributions.py#L1740-L1746

**Comment by ricardoV94** [comment]
@anirudhacharya are you still interested in the `DiscreteWeibull` or should we put it up for grabs again?

**Comment by anirudhacharya** [comment]
> @anirudhacharya are you still interested in the `DiscreteWeibull` or should we put it up for grabs again?

Please put it up for grabs.

**Comment by zoj613** [comment]
@ricardoV94 The mean looks like an infinite sum. This is a job for `scan` (seeing that the computation is meant to be symbolic) with a terminal condition based on tolerance, right? If so I can take a stab at it.

**Comment by ricardoV94** [comment]
@zoj613 we are not interested in the exact moments, but just good enough moments to start sampling. It seems the mean is quite a costly computation, so we should pick something else, perhaps the median or the mode? All we care is that the initial point always has a non-zero probability and, provided that, it is in a place with relevant prior mass

**Comment by zoj613** [comment]
> @zoj613 we are not interested in the exact moments, but just good enough moments to start sampling. It seems the mean is quite a costly computation, so we should pick something else, perhaps the median or the mode? All we care is that the initial point always has a non-zero probability and, provided that, it is in a place with relevant prior mass

Oh okay, I see. If my math is correct it looks like the mode can be computed from the CDF expression as:
```
mode = at.log(0.5) / at.log(q) - 1
```

**Comment by zoj613** [comment]
Okay I see. If my math is correct it looks like the median can be computed from the CDF expression as:
```
median = at.power(at.log(0.5) / at.log(q), 1 / beta) - 1
```

where CDF = `1 - q ** ((x + 1) ** beta)`

**Comment by ricardoV94** [comment]
> Okay I see. If my math is correct it looks like the median can be computed from the CDF expression as:
> 
> ```
> median = at.power(at.log(0.5) / at.log(q), 1 / beta) - 1
> ```
> 
> where CDF = `1 - q ** ((x + 1) ** beta)`

Great! Feel free to open a PR for it
