### ISSUE TITLE
Warn or raise explicitly for known broken features in V4

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5676]
- [x] Raise a warning when sampling with a single chain that seeding is not deterministic #5378 - Fixed by #5377
- [x] Raise an error when trying to use not yet refactored posterior_predictive_w Closed by #5799 
- [x] Raise an error when trying to use not yet refactored timeseries distributions - Closed by #5799
